version: '3.4'
services:
  kafka-cluster-1:
    image: wurstmeister/kafka
    #restart: "no"
    #restart: always
    hostname: kafka-cluster-1
    container_name: kafka-cluster-1
    ports:
       - "9097:9097"
    environment:
      KAFKA_BROKER_ID: 1        # broker id
      #KAFKA_ADVERTISED_HOST_NAME: 172.30.50.50
      KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9097
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.40.155:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: 192.168.40.155:2181   # zookeeper的連接地址
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #可有可無
    volumes:
      - /data/docker/kafka/kafka1:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
      #--------log相關----------------------------
      - ./docker_config/log4j.properties:/opt/kafka/config/log4j.properties
      - /tmp:/opt/kafka/logs
    #network_mode: "host"
  

