version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    environment:
      - cluster.name=nvt-hwc
      - node.name=elasticsearch
      - node.attr.box_type=hot
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch,es7_warm,es7_cold
      - cluster.initial_master_nodes=elasticsearch,es7_warm,es7_cold
      # - node.master=true  are deprecated,
      # - node.data=true    are deprecated,
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=elastic-certificates.p12
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=Hisharp6f
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # - ./es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12:ro
      - hwc_es7data_hot:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - proxynet
  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: es7_warm
    environment:
      - cluster.name=nvt-hwc
      - node.name=es7_warm
      - node.attr.box_type=warm
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch,es7_warm,es7_cold
      - cluster.initial_master_nodes=elasticsearch,es7_warm,es7_cold
      # - node.master=false
      # - node.data=true    are deprecated,
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=elastic-certificates.p12
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=Hisharp6f
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      #- ./es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12:ro
      - hwc_es7data_warm:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9201
    #   - 9300:9301
    networks:
      - proxynet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: es7_cold
    environment:
      - cluster.name=nvt-hwc
      - node.name=es7_cold
      - node.attr.box_type=cold
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch,es7_warm,es7_cold
      - cluster.initial_master_nodes=elasticsearch,es7_warm,es7_cold
      # - node.master=false
      # - node.data=true    are deprecated,
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=elastic-certificates.p12
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=Hisharp6f
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      #- ./es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12:ro
      - hwc_es7data_cold:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9202
    #   - 9300:9302
    networks:
      - proxynet

  logstash:
    hostname: logstash
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      # - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - proxynet
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - proxynet

volumes:
  hwc_es7data_hot:
    driver: local
  hwc_es7data_warm:
    driver: local
  hwc_es7data_cold:
    driver: local

networks:
  proxynet:
    name: elk_network

